Repository DagsHub/client, pull requests merged in 2022-12, with the labels that each got.

#247 Add libfuse3-dev to gh actions container. Handle OSError on importing fuse
  .github/workflows/python-package.yml
  dagshub/streaming/__init__.py
Labels: bug

#246 1483 - add create repo to client (for new onboarding), fix bug in upload
  dagshub/common/cli.py
  dagshub/upload/wrapper.py
  setup.py
Labels: enhancement

#239 Adjust oauth flow to use the middleman
  dagshub/auth/oauth.py
  dagshub/auth/tokens.py
  dagshub/streaming/filesystem.py
  dagshub/upload/wrapper.py
  setup.py
Labels: feature

#251 remove error about non interactive shell to fix prod bug
  dagshub/auth/oauth.py
Labels: bug
