Repository DagsHub/client, pull requests merged in 2022-11, with the labels that each got.

#216 Default to empty repo
  dagshub/upload/wrapper.py
Labels: enhancement

#218 Custom user agent for api requests
  dagshub/common/config.py
  dagshub/streaming/filesystem.py
  dagshub/upload/wrapper.py
  dagshub/version.py
  setup.py
Labels: enhancement

#234 Streaming: Add */site-packages/* to the passthrough path filter
  dagshub/streaming/filesystem.py
  tests/test_streaming_filesystem.py
Labels: enhancement

#230 Feature/create dataset repo
  dagshub/upload/__init__.py
  dagshub/upload/wrapper.py
Labels: enhancement, good first issue

#229 Added documetation to data upload code
  dagshub/common/helpers.py
  dagshub/upload/wrapper.py
Labels: documentation
