Repository DagsHub/client, pull requests merged in 2023-09, with the labels that each got.

#351 feature/support azure datasource
  dagshub/common/download.py
  dagshub/data_engine/model/datasource_state.py
  dagshub/streaming/dataclasses.py
  docs/data_engine.md
Labels: feature

#352 Fix for broken token access lock in pickling
  dagshub/auth/tokens.py
Labels: bug

#354 Bugfix: Make saving notebooks work on Windows
  dagshub/notebook.py
Labels: bug

#355 Enhancement/allow force rescan autogen columns
  dagshub/data_engine/client/data_client.py
  dagshub/data_engine/client/gql_mutations.py
  dagshub/data_engine/client/models.py
  dagshub/data_engine/model/datasource.py
Labels: enhancement

#359 Change the serialization for OAuth token to make them TZ-naive
  dagshub/auth/token_auth.py
Labels: bug

#332 External bucket support for file_column detection, dataloader post_hooks, bugfixes
  dagshub/common/api/repo.py
  dagshub/data_engine/client/loaders/base.py
  dagshub/data_engine/client/loaders/tf.py
  dagshub/data_engine/client/loaders/torch.py
Labels: bug

#360 Fix problems with blob field filter deserialization
  dagshub/data_engine/model/query.py
  tests/data_engine/test_querying.py
Labels: bug
