Repository DagsHub/client, pull requests merged in 2023-07, with the labels that each got.

#319 Fix default path on folder upload
  dagshub/upload/wrapper.py
  tests/dda/conftest.py
  tests/dda/upload/conftest.py
  tests/dda/upload/test_wrapper.py
Labels: bug

#321 dagshub upload UX improvements
  dagshub/__init__.py
  dagshub/common/cli.py
  dagshub/upload/wrapper.py
  docs/index.md
Labels: UX

#325 Check HTTP status 204 on file uploads
  dagshub/upload/wrapper.py
Labels: feature

#327 Fix URL checking of create_datasource
  dagshub/data_engine/datasources.py
  dagshub/data_engine/model/datasource_state.py
  tests/data_engine/test_datasource_state.py
Labels: bug

#331 Throw error on trying to query a field that doesn't exist in the schema
  dagshub/data_engine/client/models.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/datasource_state.py
  dagshub/data_engine/model/errors.py
  dagshub/data_engine/model/query.py
  tests/data_engine/conftest.py
  tests/data_engine/test_querying.py
  tests/data_engine/util.py
  tests/data_engine/voxel/test_filter_translation.py
Labels: enhancement

#324 Fix for mirror upload sync issues
  dagshub/common/api/repo.py
  dagshub/upload/wrapper.py
Labels: bug

#334 Fix streaming not working in Jupyter Lab/Regular IPython notebooks
  dagshub/streaming/filesystem.py
Labels: bug

#333 Enhancement/handle etag in upload
  dagshub/upload/wrapper.py
Labels: enhancement

#335 Daemonize ThreadPoolExecutor in download_files
  dagshub/common/download.py
Labels: bug

#336 Warn users about plugin not working in Colab
  dagshub/data_engine/voxel_plugin_server/plugins/dagshub/dist/index.umd.js
  dagshub/data_engine/voxel_plugin_server/server.py
Labels: bug

#337 Fix bug in upload api with a status and progress conflicting
  dagshub/upload/wrapper.py
Labels: bug
