Repository DagsHub/client, pull requests merged in 2023-05, with the labels that each got.

#279 Handle continuation token in the Storage Content API
  .github/workflows/run-linters.yaml
  dagshub/auth/token_auth.py
  dagshub/fastai/logger.py
  dagshub/keras/logger.py
  dagshub/streaming/dataclasses.py
  dagshub/streaming/filesystem.py
  tests/dda/filesystem/test_listdir.py
  tests/dda/mock_api.py
Labels: enhancement

#292 Fix wrong `.ipynb` extension logic in `save_notebook`
  dagshub/notebook.py
Labels: bug

#297 Expose `--versioning` parameter in CLI for `dagshub upload`
  dagshub/common/cli.py
  dagshub/upload/wrapper.py
Labels: bug, enhancement

#298 Repo API consolidation
  dagshub/common/api/__init__.py
  dagshub/common/api/repo.py
  dagshub/common/api/responses.py
  dagshub/streaming/dataclasses.py
  dagshub/streaming/filesystem.py
  dagshub/upload/wrapper.py
  setup.py
  tests/dda/upload/test_wrapper.py
Labels: enhancement
