Repository DagsHub/client, pull requests merged in 2023-12, with the labels that each got.

#397 Rename Field.column to Field.field_name
  dagshub/data_engine/model/datasource.py
Labels: UX

#394 Docs: add Sphinx documentation
  README.md
  dagshub/__init__.py
  dagshub/common/api/__init__.py
  dagshub/common/api/repo.py
  dagshub/common/download.py
  dagshub/common/init.py
  dagshub/data_engine/client/models.py
  dagshub/data_engine/datasets.py
  dagshub/data_engine/datasources.py
  dagshub/data_engine/dtypes.py
  dagshub/data_engine/model/datapoint.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/metadata_field_builder.py
  dagshub/data_engine/model/query_result.py
  dagshub/notebook.py
  dagshub/repo_bucket.py
  dagshub/streaming/filesystem.py
  dagshub/upload/__init__.py
  dagshub/upload/wrapper.py
  docs/Makefile
  docs/README.md
  docs/make.bat
  docs/requirements-docs.txt
  docs/source/_static/js/gtm.js
  docs/source/conf.py
  docs/source/index.rst
  docs/source/reference/data_engine/data_types.rst
  docs/source/reference/data_engine/datapoint.rst
  docs/source/reference/data_engine/datasource.rst
  docs/source/reference/data_engine/index.rst
  docs/source/reference/data_engine/query_result.rst
  docs/source/reference/file_downloading.rst
  docs/source/reference/file_uploading.rst
  docs/source/reference/metric_logging.rst
  docs/source/reference/notebook.rst
  docs/source/reference/repo_api.rst
  docs/source/reference/repo_bucket.rst
  docs/source/reference/setup.rst
Labels: documentation, wip

#403 Docs: add Authentication section
  dagshub/auth/tokens.py
  docs/source/index.rst
  docs/source/reference/auth.rst
Labels: documentation

#404 Remove the note about the backend not generating automatic aliases
  dagshub/data_engine/model/datasource.py
Labels: documentation

#401 include/ exclude list for LS meta-data
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/query_result.py
  docs/data_engine.md
Labels: enhancement

#406 Mark the datasource saving functions as experimental
  dagshub/data_engine/datasets.py
  dagshub/data_engine/datasources.py
  dagshub/data_engine/model/datasource.py
Labels: documentation

#407 Fix incorrect doc formatting in Datasource.annotate()
  dagshub/data_engine/model/datasource.py
Labels: documentation

#409 Bugfix: Fixed a faulty null check
  dagshub/data_engine/model/datasource_state.py
Labels: bug

#400 Add a GitHub Action to build and upload docs to a GCS Bucket
  .github/workflows/docs-publish.yml
  docs/source/conf.py
Labels: documentation
