Repository DagsHub/client, pull requests merged in 2024-07, with the labels that each got.

#493 Enhancement / Print “accessing as <user>” in client
  dagshub/auth/tokens.py
  tests/common/test_determine_repo.py
  tests/data_engine/conftest.py
  tests/data_engine/test_datasource_state.py
  tests/dda/mock_api.py
  tests/dda/test_tokens.py
  tests/util.py
Labels: enhancement

#499 Fix OAuth token redemption breaking
  dagshub/auth/tokens.py
Labels: bug

#502 Add retry to the download function
  dagshub/common/download.py
Labels: enhancement

#506 Bug: Filter the metadata fields based on the introspection
  dagshub/data_engine/client/gql_queries.py
Labels: bug

#510 Tests: Pin path lib to 16.0.0
  requirements-dev.txt
Labels: bug, tests

#509 Enhancement: Add explanation of what install_hooks() is doing
  dagshub/streaming/filesystem.py
Labels: enhancement
