Repository DagsHub/client, pull requests merged in 2024-03, with the labels that each got.

#442 Add s3 upload functionality in `dagshub.upload` and in cli `dagshub upload`
  .gitignore
  dagshub/common/cli.py
  dagshub/common/config.py
  dagshub/upload/wrapper.py
  setup.py
Labels: enhancement

#443 Bug: Make the client work even when git is not installed
  dagshub/common/determine_repo.py
  dagshub/common/init.py
Labels: bug

#440 feature/support select fields
  .github/workflows/run-linters.yaml
  dagshub/auth/oauth.py
  dagshub/auth/token_auth.py
  dagshub/common/api/__init__.py
  dagshub/common/cli.py
  dagshub/common/determine_repo.py
  dagshub/common/errors.py
  dagshub/common/helpers.py
  dagshub/data_engine/client/data_client.py
  dagshub/data_engine/client/gql_introspections.py
  dagshub/data_engine/client/gql_queries.py
  dagshub/data_engine/dtypes.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/errors.py
  dagshub/data_engine/model/query_result.py
  dagshub/streaming/dataclasses.py
  docs/source/conf.py
  examples/keras/mnist.py
  examples/pytorch-lightning/hyperparams-as-dependency/mnist_trainer.py
  examples/pytorch-lightning/hyperparams-as-output/mnist_trainer.py
  examples/pytorch-lightning/mnist_model.py
  setup.py
  tests/data_engine/test_datasource.py
  tests/data_engine/test_datasource_state.py
  tests/data_engine/test_queryresult.py
  tests/data_engine/util.py
  tests/data_engine/voxel/test_filter_translation.py
  tests/dda/conftest.py
  tests/dda/filesystem/test_misc.py
  tests/dda/mock_api.py
  tests/dda/test_tokens.py
  tests/dda/upload/test_wrapper.py
  tests/test_dagshub_logger.py
  tests/test_misc.py
Labels: feature

#445 Tests: add tests for os.path.isfile/isdir for streaming
  tests/dda/filesystem/test_misc.py
  tests/dda/mock_api.py
Labels: tests

#450 Add storage convenience features for mounting and syncing with rclone
  dagshub/__init__.py
  dagshub/storage/__init__.py
  dagshub/storage/rclone.py
  docs/source/reference/repo_bucket.rst
Labels: enhancement, feature

#444 Add ability to visualize in the dagshub gallery view
  dagshub/common/__init__.py
  dagshub/common/notebook.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/datasource_state.py
  dagshub/data_engine/model/query_result.py
Labels: enhancement

#454 Data Engine: Add a progress bar for blob downloading
  dagshub/data_engine/model/datapoint.py
  dagshub/data_engine/model/query_result.py
Labels: enhancement

#447 Loading a model from DagsHub repo using `get_model_path`
  dagshub/common/download.py
  dagshub/models/__init__.py
  dagshub/models/model_loaders.py
  dagshub/models/model_locator.py
  docs/source/index.rst
  docs/source/reference/loading_models.rst
  tests/mocks/__init__.py
  tests/mocks/repo_api.py
  tests/model_loading/__init__.py
  tests/model_loading/conftest.py
  tests/model_loading/test_locate.py
Labels: feature

#458 Add a dagshub.colab.login command
  dagshub/auth/oauth.py
  dagshub/auth/tokens.py
  dagshub/colab/__init__.py
  dagshub/colab/login.py
  docs/source/reference/notebook.rst
Labels: enhancement
