Repository DagsHub/client, pull requests merged in 2024-02, with the labels that each got.

#362 DDA Streaming: allow excluding certain glob patterns from being looked up
  dagshub/streaming/dataclasses.py
  dagshub/streaming/filesystem.py
  dagshub/upload/wrapper.py
  tests/dda/filesystem/test_open.py
Labels: enhancement

#426 Docs: Add example usage snippets for the bucket client flavors
  dagshub/repo_bucket.py
Labels: documentation

#410 Save/Load Datasource/Dataset state from MLflow
  dagshub/common/config.py
  dagshub/common/init.py
  dagshub/common/util.py
  dagshub/data_engine/client/data_client.py
  dagshub/data_engine/client/models.py
  dagshub/data_engine/datasets.py
  dagshub/data_engine/datasources.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/query.py
  dagshub/data_engine/voxel_plugin_server/models.py
  dagshub/data_engine/voxel_plugin_server/routes/voxel.py
  tests/data_engine/conftest.py
  tests/data_engine/test_querying.py
Labels: enhancement

#430 dagshub upload: variable batch size.
  dagshub/upload/wrapper.py
Labels: UX

#433 Fix an issue where large colab notebooks would fail saving due to timeout
  dagshub/notebook.py
Labels: bug, UX

#432 Feature/Support sorting
  dagshub/data_engine/client/data_client.py
  dagshub/data_engine/client/gql_introspections.py
  dagshub/data_engine/client/gql_queries.py
  dagshub/data_engine/client/query_builder/__init__.py
  dagshub/data_engine/model/datasource.py
Labels: feature

#431 Add tenacity + retry on internal server errors in dagshub upload
  dagshub/upload/wrapper.py
  setup.py
Labels: UX

#434 Streaming: Add ability to monkey-patched non-python opens
  dagshub/streaming/filesystem.py
Labels: enhancement

#389 Add ability to download a repo folder (including CLI)
  dagshub/common/api/repo.py
  dagshub/common/cli.py
Labels: enhancement, UX

#436 FIftyOne: Unpack the new tuple that gets returned from the ls converter
  dagshub/data_engine/annotation/voxel_conversion.py
Labels: bug

#424 delete metadata
  dagshub/data_engine/client/data_client.py
  dagshub/data_engine/client/gql_mutations.py
  dagshub/data_engine/model/datapoint.py
  dagshub/data_engine/model/datasource.py
Labels: enhancement
