Repository DagsHub/client, pull requests merged in 2024-09, with the labels that each got.

#520 Feature/autolog datasource id
  dagshub/data_engine/model/datasource.py
Labels: enhancement, feature

#522 Infra: Unpin semver dependencies
  setup.py
Labels: dependencies

#526 Fix wrong example args for ds.import_annotations_from_files
  dagshub/data_engine/model/datasource.py
Labels: documentation

#531 Add a fallback on annotation validation
  dagshub/data_engine/model/query_result.py
Labels: bug

#532 Drop Python 3.7 support
  setup.py
Labels: dependencies
