Repository DagsHub/client, pull requests merged in 2025-02, with the labels that each got.

#588 Limit boto3<1.36.0
  setup.py
Labels: bug

#590 Feature: Limits as part of the query
  dagshub/common/util.py
  dagshub/data_engine/annotation/metadata.py
  dagshub/data_engine/client/gql_introspections.py
  dagshub/data_engine/client/gql_mutations.py
  dagshub/data_engine/client/gql_queries.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/query.py
  dagshub/data_engine/model/query_result.py
Labels: feature

#593 Bug: Can't upload MetadataAnnotations through dataframe
  dagshub/common/util.py
  dagshub/data_engine/model/datasource.py
  dagshub/data_engine/model/metadata/__init__.py
  dagshub/data_engine/model/metadata/dtypes.py
  dagshub/data_engine/model/metadata/transforms.py
  dagshub/data_engine/model/metadata/util.py
  dagshub/data_engine/model/schema_util.py
  tests/data_engine/conftest.py
  tests/data_engine/test_datasource.py
  tests/data_engine/test_datasource_state.py
  tests/data_engine/util.py
Labels: bug, enhancement

#595 Bug: refetch fields on has_field failure
  dagshub/data_engine/model/datasource.py
Labels: bug

#596 Tests: Fix platform-dependent path objects breaking on windows
  tests/dda/upload/test_wrapper.py
  tests/model_loading/test_locate.py
Labels: tests

#598 Bug: Nested folders upload incorrectly on windows
  dagshub/upload/wrapper.py
Labels: bug

#599 Fix ds.all() so that it passes load_* args to ds.fetch()
  dagshub/data_engine/model/datasource.py
Labels: bug
